name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Date for incremental models
  start_date: '2024-01-01'
  # Minimum session duration in seconds
  min_session_duration: 10
  # Maximum session duration in hours
  max_session_hours: 24
  # Session timeout in minutes
  session_timeout_minutes: 30

models:
  ecommerce_analytics:
    # Staging models - raw data cleaning
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging', 'daily']

    # Intermediate models - business logic
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ['intermediate', 'daily']

    # Marts - final analytics tables
    marts:
      +materialized: table
      +schema: analytics
      +tags: ['marts', 'daily']

seeds:
  ecommerce_analytics:
    +schema: seeds

tests:
  ecommerce_analytics:
    +severity: warn
